import Character1 from "./assets/images/LeaderBoard/Characters/AnimateProfile1.png";
import Character2 from "./assets/images/LeaderBoard/Characters/AnimateProfile2.png";
import Character3 from "./assets/images/LeaderBoard/Characters/AnimateProfile3.png";
import Character4 from "./assets/images/LeaderBoard/Characters/AnimateProfile4.png";
import Character5 from "./assets/images/LeaderBoard/Characters/AnimateProfile5.png";
import Character6 from "./assets/images/LeaderBoard/Characters/AnimateProfile6.png";
import Character7 from "./assets/images/LeaderBoard/Characters/AnimateProfile7.png";
import Character8 from "./assets/images/LeaderBoard/Characters/AnimateProfile8.png";
import Character9 from "./assets/images/LeaderBoard/Characters/AnimateProfile9.png";
import Character10 from "./assets/images/LeaderBoard/Characters/AnimateProfile10.png";

import Badge1 from "./assets/images/LeaderBoard/Badges/1stPlace.png";
import Badge2 from "./assets/images/LeaderBoard/Badges/2ndPlace.png";
import Badge3 from "./assets/images/LeaderBoard/Badges/3rdPlace.png";
import Badge4 from "./assets/images/LeaderBoard/Badges/4Place.png";
import Badge5 from "./assets/images/LeaderBoard/Badges/5Place.png";
import Badge6 from "./assets/images/LeaderBoard/Badges/6Place.png";
import Badge7 from "./assets/images/LeaderBoard/Badges/7Place.png";
import Badge8 from "./assets/images/LeaderBoard/Badges/8Place.png";
import Badge9 from "./assets/images/LeaderBoard/Badges/9Place.png";
import Badge10 from "./assets/images/LeaderBoard/Badges/10Place.png";

export const HomeData = [
  {
    id: 1,
    Title: "Suscipit Omnis Aut Debitis",
    description:
      "Etiam sit amet urna non nunc mattis suscipit. Orci varius natoque penatibus et magnis dis parturient montes.",
    // Picture: "https://cvbay.com/wp-content/uploads/2017/03/dummy-image.jpg",
    Picture: "",
    CreatedAt: "4 days ago",
  },
  {
    id: 2,
    Title: "Aut Illo Quas Beatae",
    description:
      "Etiam sit amet urna non nunc mattis suscipit. Orci varius natoque penatibus et magnis dis parturient montes.",
    Picture: "",
    CreatedAt: "5 days ago",
  },
  {
    id: 3,
    Title: "Consectetur Distinctio Ab Dolor",
    description:
      "Etiam sit amet urna non nunc mattis suscipit. Orci varius natoque penatibus et magnis dis parturient montes.",
    Picture: "",
    CreatedAt: "10 days ago",
  },
  {
    id: 4,
    Title: "Quo Ut Vel Assumenda",
    description:
      "Etiam sit amet urna non nunc mattis suscipit. Orci varius natoque penatibus et magnis dis parturient montes.",
    Picture: "",
    CreatedAt: "1 month ago",
  },
  {
    id: 5,
    Title: "Repellat Enim Velit Numquam",
    description:
      "Etiam sit amet urna non nunc mattis suscipit. Orci varius natoque penatibus et magnis dis parturient montes.",
    Picture: "",
    CreatedAt: "2 month ago",
  },
  {
    id: 6,
    Title: "Dolores Expedita In Cupiditate",
    description:
      "Etiam sit amet urna non nunc mattis suscipit. Orci varius natoque penatibus et magnis dis parturient montes.",
    Picture: "",
    CreatedAt: "2 month ago",
  },
  {
    id: 7,
    Title: "Qui Delectus Aut Impedit",
    description:
      "Etiam sit amet urna non nunc mattis suscipit. Orci varius natoque penatibus et magnis dis parturient montes.",
    Picture: "",
    CreatedAt: "2 month ago",
  },
  {
    id: 8,
    Title: "Quisquam Ea Distinctio Quia",
    description:
      "Etiam sit amet urna non nunc mattis suscipit. Orci varius natoque penatibus et magnis dis parturient montes.",
    Picture: "",
    CreatedAt: "2 month ago",
  },
];
export const LeaderBoardData = [
  {
    id: 1,
    Name: "John Snow",
    Picture: Character1,
    position: Badge1,
    Level: "60",
    coins: "60",
  },
  {
    id: 2,
    Name: "Eddie Shaw",
    Picture: Character2,
    position: Badge2,
    Level: "50",
    coins: "50",
  },
  {
    id: 3,
    Name: "Swae Lee",
    Picture: Character3,
    position: Badge3,
    Level: "45",
    coins: "10",
  },
  {
    id: 4,
    Name: "Rhonda Kuphal",
    Picture: Character4,
    position: Badge4,
    Level: "40",
    coins: "40",
  },
  {
    id: 5,
    Name: "Leslie Murphy",
    Picture: Character5,
    position: Badge5,
    Level: "35",
    coins: "27",
  },
  {
    id: 6,
    Name: "Olive Rau II",
    Picture: Character6,
    position: Badge6,
    Level: "20",
    coins: "25",
  },
  {
    id: 7,
    Name: "Jimmie Koss DVM",
    Picture: Character7,
    position: Badge7,
    Level: "16",
    coins: "25",
  },
  {
    id: 8,
    Name: "Johanna Wintheiser IV",
    Picture: Character8,
    position: Badge8,
    Level: "14",
    coins: "20",
  },
  {
    id: 9,
    Name: "Cornelius Gerhold",
    Picture: Character9,
    position: Badge9,
    Level: "10",
    coins: "20",
  },
  {
    id: 10,
    Name: "Beatrice Mohr",
    Picture: Character10,
    position: Badge10,
    Level: "9",
    coins: "10",
  },
];

// export const PaymentCards = [
//   { id: 1, CardNum: "4242424242424242", CardType: "Mastercard" },
//   { id: 1, CardNum: "4545454545454545", CardType: "PayPal" },
//   { id: 1, CardNum: "8747483947585958", CardType: "Visa" },
// ];

export const ListTask = [
  {
    id: 1,
    date: "08",
    month: "June",
    tasks: [
      {
        id: 1,
        Title: "Dolor Qui Omnia",
        description:
          "Renum corporis dolore. Ad provident magnam er exervitationem.A sit rerum",
        Time: "2:53 Pm",
        date: "Wednesday, 13 April, 2021 09:00PM",
        detail:
          "Voluptate non error tempora sunt optio dolores labore dolorem. Dignissimos iste quam illo dignissimos rerum quia. Molestiae autem ut voluptas esse repellendus illum beatae. Vel nostrum nemo vero id veritatis tenetur saepe. Dignissimos iste quam illo dignissimos rerum quia. Dignissimos iste quam illo dignissimos rerum quia.",
        status: "In-Progress",
        Repeat: "Daily",
        BlockApps: "Facebook,Whatspp,Instagram",
      },
      {
        id: 1,
        Title: "Unde Delectus Officia",
        description:
          "Renum corporis dolore. Ad provident magnam er exervitationem.A sit rerum",
        Time: "2:53 Pm",
        date: "Wednesday, 13 April, 2021 09:00PM",
        detail:
          "Voluptate non error tempora sunt optio dolores labore dolorem. Dignissimos iste quam illo dignissimos rerum quia. Molestiae autem ut voluptas esse repellendus illum beatae. Vel nostrum nemo vero id veritatis tenetur saepe. Dignissimos iste quam illo dignissimos rerum quia. Dignissimos iste quam illo dignissimos rerum quia.",
        status: "In-Progress",
        Repeat: "Daily",
        BlockApps: "Facebook,Instagram",
      },
      {
        id: 1,
        Title: "Voluptatem Voluptas",
        description:
          "Renum corporis dolore. Ad provident magnam er exervitationem.A sit rerum",
        Time: "2:53 Pm",
        date: "Wednesday, 13 April, 2021 09:00PM",
        detail:
          "Voluptate non error tempora sunt optio dolores labore dolorem. Dignissimos iste quam illo dignissimos rerum quia. Molestiae autem ut voluptas esse repellendus illum beatae. Vel nostrum nemo vero id veritatis tenetur saepe. Dignissimos iste quam illo dignissimos rerum quia. Dignissimos iste quam illo dignissimos rerum quia.",
        status: "In-Progress",
        Repeat: "Daily",
        BlockApps: "Whatspp,Instagram",
      },
      {
        id: 1,
        Title: "Nemo Deleniti Sit",
        description:
          "Renum corporis dolore. Ad provident magnam er exervitationem.A sit rerum",
        Time: "2:53 Pm",
        date: "Wednesday, 13 April, 2021 09:00PM",
        detail:
          "Voluptate non error tempora sunt optio dolores labore dolorem. Dignissimos iste quam illo dignissimos rerum quia. Molestiae autem ut voluptas esse repellendus illum beatae. Vel nostrum nemo vero id veritatis tenetur saepe. Dignissimos iste quam illo dignissimos rerum quia. Dignissimos iste quam illo dignissimos rerum quia.",
        status: "In-Progress",
        Repeat: "Daily",
        BlockApps: "Whatspp,Instagram",
      },
    ],
  },
  {
    id: 1,
    date: "07",
    month: "June",
    tasks: [
      {
        id: 1,
        Title: "Dolor Qui Omnia",
        description:
          "Renum corporis dolore. Ad provident magnam er exervitationem.A sit rerum",
        Time: "2:53 Pm",
        date: "Wednesday, 13 April, 2021 09:00PM",
        detail:
          "Voluptate non error tempora sunt optio dolores labore dolorem. Dignissimos iste quam illo dignissimos rerum quia. Molestiae autem ut voluptas esse repellendus illum beatae. Vel nostrum nemo vero id veritatis tenetur saepe. Dignissimos iste quam illo dignissimos rerum quia. Dignissimos iste quam illo dignissimos rerum quia.",
        status: "In-Progress",
        Repeat: "Daily",
        BlockApps: "Instagram",
      },
      {
        id: 1,
        Title: "Unde Delectus Officia",
        description:
          "Renum corporis dolore. Ad provident magnam er exervitationem.A sit rerum",
        Time: "2:53 Pm",
        date: "Wednesday, 13 April, 2021 09:00PM",
        detail:
          "Voluptate non error tempora sunt optio dolores labore dolorem. Dignissimos iste quam illo dignissimos rerum quia. Molestiae autem ut voluptas esse repellendus illum beatae. Vel nostrum nemo vero id veritatis tenetur saepe. Dignissimos iste quam illo dignissimos rerum quia. Dignissimos iste quam illo dignissimos rerum quia.",
        status: "In-Progress",
        Repeat: "Daily",
        BlockApps: "Whatspp",
      },
    ],
  },
  {
    id: 1,
    date: "06",
    month: "June",
    tasks: [
      {
        id: 1,
        Title: "Unde Delectus Officia",
        description:
          "Renum corporis dolore. Ad provident magnam er exervitationem.A sit rerum",
        Time: "2:53 Pm",
        date: "Wednesday, 13 April, 2021 09:00PM",
        detail:
          "Voluptate non error tempora sunt optio dolores labore dolorem. Dignissimos iste quam illo dignissimos rerum quia. Molestiae autem ut voluptas esse repellendus illum beatae. Vel nostrum nemo vero id veritatis tenetur saepe. Dignissimos iste quam illo dignissimos rerum quia. Dignissimos iste quam illo dignissimos rerum quia.",
        status: "In-Progress",
        Repeat: "Daily",
        BlockApps: "Facebook,Instagram",
      },
      {
        id: 1,
        Title: "Nemo Deleniti Sit",
        description:
          "Renum corporis dolore. Ad provident magnam er exervitationem.A sit rerum",
        Time: "2:53 Pm",
        date: "Wednesday, 13 April, 2021 09:00PM",
        detail:
          "Voluptate non error tempora sunt optio dolores labore dolorem. Dignissimos iste quam illo dignissimos rerum quia. Molestiae autem ut voluptas esse repellendus illum beatae. Vel nostrum nemo vero id veritatis tenetur saepe. Dignissimos iste quam illo dignissimos rerum quia. Dignissimos iste quam illo dignissimos rerum quia.",
        status: "In-Progress",
        Repeat: "Daily",
        BlockApps: "Facebook,Instagram",
      },
      {
        id: 1,
        Title: "Dolor Qui Omnia",
        description:
          "Renum corporis dolore. Ad provident magnam er exervitationem.A sit rerum",
        Time: "2:53 Pm",
        date: "Wednesday, 13 April, 2021 09:00PM",
        detail:
          "Voluptate non error tempora sunt optio dolores labore dolorem. Dignissimos iste quam illo dignissimos rerum quia. Molestiae autem ut voluptas esse repellendus illum beatae. Vel nostrum nemo vero id veritatis tenetur saepe. Dignissimos iste quam illo dignissimos rerum quia. Dignissimos iste quam illo dignissimos rerum quia.",
        status: "In-Progress",
        Repeat: "Daily",
        BlockApps: "Facebook,Whatspp",
      },
    ],
  },
];
// export const TaskListDetail = [
//   {
//     id: 1,
//     Title: 'Read 3 Page of "Atomic Habits"',
//     description:
//       "Etiam sit amet urna non nunc mattis suscipit. Orci varius natoque penatibus et magnis dis parturient montes.",
//     Picture: "",
//     CreatedAt: "4 days ago",
//     date: "Wednesday, 13 April, 2021 09:00PM",
//     detail:
//       "Voluptate non error tempora sunt optio dolores labore dolorem. Dignissimos iste quam illo dignissimos rerum quia. Molestiae autem ut voluptas esse repellendus illum beatae. Vel nostrum nemo vero id veritatis tenetur saepe. Dignissimos iste quam illo dignissimos rerum quia. Dignissimos iste quam illo dignissimos rerum quia.",
//     status: "Completed",
//     Repeat: "Daily",
//     BlockApps: "Facebook,Whatspp,Instagram",
//   },
//   {
//     id: 2,
//     Title: "Aut Illo Quas Beatae",
//     description:
//       "Etiam sit amet urna non nunc mattis suscipit. Orci varius natoque penatibus et magnis dis parturient montes.",
//     Picture: "",
//     CreatedAt: "4 days ago",
//     date: "Wednesday, 13 April, 2021 09:00PM",
//     detail:
//       "Voluptate non error tempora sunt optio dolores labore dolorem. Dignissimos iste quam illo dignissimos rerum quia. Molestiae autem ut voluptas esse repellendus illum beatae. Vel nostrum nemo vero id veritatis tenetur saepe. Dignissimos iste quam illo dignissimos rerum quia. Dignissimos iste quam illo dignissimos rerum quia.",
//     status: "Completed",
//     Repeat: "Daily",
//     BlockApps: "Instagram",
//   },
//   {
//     id: 3,
//     Title: "Consectetur Distinctio Ab Dolor",
//     description:
//       "Etiam sit amet urna non nunc mattis suscipit. Orci varius natoque penatibus et magnis dis parturient montes.",
//     Picture: "",
//     CreatedAt: "4 days ago",
//     date: "Wednesday, 13 April, 2021 09:00PM",
//     detail:
//       "Voluptate non error tempora sunt optio dolores labore dolorem. Dignissimos iste quam illo dignissimos rerum quia. Molestiae autem ut voluptas esse repellendus illum beatae. Vel nostrum nemo vero id veritatis tenetur saepe. Dignissimos iste quam illo dignissimos rerum quia. Dignissimos iste quam illo dignissimos rerum quia.",
//     status: "Completed",
//     Repeat: "Daily",
//     BlockApps: "Facebook,Instagram",
//   },
//   {
//     id: 4,
//     Title: "Quo Ut Vel Assumenda",
//     description:
//       "Etiam sit amet urna non nunc mattis suscipit. Orci varius natoque penatibus et magnis dis parturient montes.",
//     Picture: "",
//     CreatedAt: "5 days ago",
//     date: "Wednesday, 13 April, 2021 09:00PM",
//     detail:
//       "Voluptate non error tempora sunt optio dolores labore dolorem. Dignissimos iste quam illo dignissimos rerum quia. Molestiae autem ut voluptas esse repellendus illum beatae. Vel nostrum nemo vero id veritatis tenetur saepe. Dignissimos iste quam illo dignissimos rerum quia. Dignissimos iste quam illo dignissimos rerum quia.",
//     status: "Completed",
//     Repeat: "Daily",
//     BlockApps: "Facebook,Whatspp,Instagram",
//   },
//   {
//     id: 5,
//     Title: "Repellat Enim Velit Numquam",
//     description:
//       "Etiam sit amet urna non nunc mattis suscipit. Orci varius natoque penatibus et magnis dis parturient montes.",
//     Picture: "",
//     CreatedAt: "9 days ago",
//     date: "Wednesday, 13 April, 2021 09:00PM",
//     detail:
//       "Voluptate non error tempora sunt optio dolores labore dolorem. Dignissimos iste quam illo dignissimos rerum quia. Molestiae autem ut voluptas esse repellendus illum beatae. Vel nostrum nemo vero id veritatis tenetur saepe. Dignissimos iste quam illo dignissimos rerum quia. Dignissimos iste quam illo dignissimos rerum quia.",
//     status: "Completed",
//     Repeat: "Daily",
//     BlockApps: "Facebook,Whatspp,Instagram",
//   },
//   {
//     id: 6,
//     Title: "Dolores Expedita In Cupiditate",
//     description:
//       "Etiam sit amet urna non nunc mattis suscipit. Orci varius natoque penatibus et magnis dis parturient montes.",
//     Picture: "",
//     CreatedAt: "10 days ago",
//     date: "Wednesday, 13 April, 2021 09:00PM",
//     detail:
//       "Voluptate non error tempora sunt optio dolores labore dolorem. Dignissimos iste quam illo dignissimos rerum quia. Molestiae autem ut voluptas esse repellendus illum beatae. Vel nostrum nemo vero id veritatis tenetur saepe. Dignissimos iste quam illo dignissimos rerum quia. Dignissimos iste quam illo dignissimos rerum quia.",
//     status: "Completed",
//     Repeat: "Daily",
//     BlockApps: "Facebook,Whatspp",
//   },
//   {
//     id: 7,
//     Title: "Qui Delectus Aut Impedit",
//     description:
//       "Etiam sit amet urna non nunc mattis suscipit. Orci varius natoque penatibus et magnis dis parturient montes.",
//     Picture: "",
//     CreatedAt: "10 days ago",
//     date: "Wednesday, 13 April, 2021 09:00PM",
//     detail:
//       "Voluptate non error tempora sunt optio dolores labore dolorem. Dignissimos iste quam illo dignissimos rerum quia. Molestiae autem ut voluptas esse repellendus illum beatae. Vel nostrum nemo vero id veritatis tenetur saepe. Dignissimos iste quam illo dignissimos rerum quia. Dignissimos iste quam illo dignissimos rerum quia.",
//     status: "Completed",
//     Repeat: "Daily",
//     BlockApps: "Facebook,Instagram",
//   },
//   {
//     id: 8,
//     Title: "Quisquam Ea Distinctio Quia",
//     description:
//       "Etiam sit amet urna non nunc mattis suscipit. Orci varius natoque penatibus et magnis dis parturient montes.",
//     Picture: "",
//     CreatedAt: "12 days ago",
//     date: "Wednesday, 13 April, 2021 09:00PM",
//     detail:
//       "Voluptate non error tempora sunt optio dolores labore dolorem. Dignissimos iste quam illo dignissimos rerum quia. Molestiae autem ut voluptas esse repellendus illum beatae. Vel nostrum nemo vero id veritatis tenetur saepe. Dignissimos iste quam illo dignissimos rerum quia. Dignissimos iste quam illo dignissimos rerum quia.",
//     status: "Completed",
//     Repeat: "Daily",
//     BlockApps: "Facebook,Instagram",
//   },
// ];
// export const MYdailyNotes = [
//   {
//     id: 1,
//     Title: "Dolor Qui Omnia",
//     description:
//       "Etiam sit amet urna non nunc mattis suscipit. Orci varius natoque penatibus et magnis dis parturient montes.",
//     Picture: "",
//     CreatedAt: "4 days ago",
//     date: "Wednesday, 13 April, 2021 09:00PM",
//     detail:
//       "Voluptate non error tempora sunt optio dolores labore dolorem. Dignissimos iste quam illo dignissimos rerum quia. Molestiae autem ut voluptas esse repellendus illum beatae. Vel nostrum nemo vero id veritatis tenetur saepe. Dignissimos iste quam illo dignissimos rerum quia. Dignissimos iste quam illo dignissimos rerum quia.",
//     status: "Completed",
//   },
//   {
//     id: 2,
//     Title: "Aut Illo Quas Beatae",
//     description:
//       "Etiam sit amet urna non nunc mattis suscipit. Orci varius natoque penatibus et magnis dis parturient montes.",
//     Picture: "",
//     CreatedAt: "4 days ago",
//     date: "Wednesday, 13 April, 2021 09:00PM",
//     detail:
//       "Voluptate non error tempora sunt optio dolores labore dolorem. Dignissimos iste quam illo dignissimos rerum quia. Molestiae autem ut voluptas esse repellendus illum beatae. Vel nostrum nemo vero id veritatis tenetur saepe. Dignissimos iste quam illo dignissimos rerum quia. Dignissimos iste quam illo dignissimos rerum quia.",
//     status: "Completed",
//   },
//   {
//     id: 3,
//     Title: "Consectetur Distinctio Ab Dolor",
//     description:
//       "Etiam sit amet urna non nunc mattis suscipit. Orci varius natoque penatibus et magnis dis parturient montes.",
//     Picture: "",
//     CreatedAt: "4 days ago",
//     date: "Wednesday, 13 April, 2021 09:00PM",
//     detail:
//       "Voluptate non error tempora sunt optio dolores labore dolorem. Dignissimos iste quam illo dignissimos rerum quia. Molestiae autem ut voluptas esse repellendus illum beatae. Vel nostrum nemo vero id veritatis tenetur saepe. Dignissimos iste quam illo dignissimos rerum quia. Dignissimos iste quam illo dignissimos rerum quia.",
//     status: "Completed",
//   },
//   {
//     id: 4,
//     Title: "Quo Ut Vel Assumenda",
//     description:
//       "Etiam sit amet urna non nunc mattis suscipit. Orci varius natoque penatibus et magnis dis parturient montes.",
//     Picture: "",
//     CreatedAt: "5 days ago",
//     date: "Wednesday, 13 April, 2021 09:00PM",
//     detail:
//       "Voluptate non error tempora sunt optio dolores labore dolorem. Dignissimos iste quam illo dignissimos rerum quia. Molestiae autem ut voluptas esse repellendus illum beatae. Vel nostrum nemo vero id veritatis tenetur saepe. Dignissimos iste quam illo dignissimos rerum quia. Dignissimos iste quam illo dignissimos rerum quia.",
//     status: "Completed",
//   },
//   {
//     id: 5,
//     Title: "Repellat Enim Velit Numquam",
//     description:
//       "Etiam sit amet urna non nunc mattis suscipit. Orci varius natoque penatibus et magnis dis parturient montes.",
//     Picture: "",
//     CreatedAt: "9 days ago",
//     date: "Wednesday, 13 April, 2021 09:00PM",
//     detail:
//       "Voluptate non error tempora sunt optio dolores labore dolorem. Dignissimos iste quam illo dignissimos rerum quia. Molestiae autem ut voluptas esse repellendus illum beatae. Vel nostrum nemo vero id veritatis tenetur saepe. Dignissimos iste quam illo dignissimos rerum quia. Dignissimos iste quam illo dignissimos rerum quia.",
//     status: "Completed",
//   },
//   {
//     id: 6,
//     Title: "Dolores Expedita In Cupiditate",
//     description:
//       "Etiam sit amet urna non nunc mattis suscipit. Orci varius natoque penatibus et magnis dis parturient montes.",
//     Picture: "",
//     CreatedAt: "10 days ago",
//     date: "Wednesday, 13 April, 2021 09:00PM",
//     detail:
//       "Voluptate non error tempora sunt optio dolores labore dolorem. Dignissimos iste quam illo dignissimos rerum quia. Molestiae autem ut voluptas esse repellendus illum beatae. Vel nostrum nemo vero id veritatis tenetur saepe. Dignissimos iste quam illo dignissimos rerum quia. Dignissimos iste quam illo dignissimos rerum quia.",
//     status: "Completed",
//   },
//   {
//     id: 7,
//     Title: "Qui Delectus Aut Impedit",
//     description:
//       "Etiam sit amet urna non nunc mattis suscipit. Orci varius natoque penatibus et magnis dis parturient montes.",
//     Picture: "",
//     CreatedAt: "10 days ago",
//     date: "Wednesday, 13 April, 2021 09:00PM",
//     detail:
//       "Voluptate non error tempora sunt optio dolores labore dolorem. Dignissimos iste quam illo dignissimos rerum quia. Molestiae autem ut voluptas esse repellendus illum beatae. Vel nostrum nemo vero id veritatis tenetur saepe. Dignissimos iste quam illo dignissimos rerum quia. Dignissimos iste quam illo dignissimos rerum quia.",
//     status: "Completed",
//   },
//   {
//     id: 8,
//     Title: "Quisquam Ea Distinctio Quia",
//     description:
//       "Etiam sit amet urna non nunc mattis suscipit. Orci varius natoque penatibus et magnis dis parturient montes.",
//     Picture: "",
//     CreatedAt: "12 days ago",
//     date: "Wednesday, 13 April, 2021 09:00PM",
//     detail:
//       "Voluptate non error tempora sunt optio dolores labore dolorem. Dignissimos iste quam illo dignissimos rerum quia. Molestiae autem ut voluptas esse repellendus illum beatae. Vel nostrum nemo vero id veritatis tenetur saepe. Dignissimos iste quam illo dignissimos rerum quia. Dignissimos iste quam illo dignissimos rerum quia.",
//     status: "Completed",
//   },
// ];

// export const RewardsList = [
//   {
//     id: 1,
//     points: "+1,000 Points",
//     IMG: SVGImages.Trouphy,
//   },
//   {
//     id: 2,
//     points: "1x Golden Sword",
//     IMG: SVGImages.Sword,
//   },
//   {
//     id: 3,
//     points: "1x Golden Shield",
//     IMG: SVGImages.Shield,
//   },
//   {
//     id: 4,
//     points: "500 Gold Bricks",
//     IMG: SVGImages.GoldBrick,
//   },
// ];

// export const AllRewardList = [
//   {
//     id: 1,
//     IMG: images.Rewards1,
//     title: "Quia Ad",
//     detail: "odio occaecati sit ut suscipit",
//     Status: "Incomplete",
//     Progress: "47/200",
//     points: "1x Golden Shield",
//     requriment: ["• Complete 10 tasks in one week.", "• Level 23 must."],
//     TaskStatus: "6/10",
//   },
//   {
//     id: 2,
//     IMG: images.Rewards2,
//     title: "Eligendi Est",
//     detail: "iure similique non aut cumque",
//     Status: "Incomplete",
//     Progress: "89/200",
//     points: "1x Cronw Shield",
//     requriment: ["• Complete 10 tasks in one week.", "• Level 23 must."],
//     TaskStatus: "6/10",
//   },
//   {
//     id: 3,
//     IMG: images.Rewards4,
//     title: "Ipsa Omnis",
//     detail: "debitis laudantium maiores qui animi",
//     Status: "Incomplete",
//     Progress: "63/200",
//     points: "500 Gold Bricks",
//     requriment: ["• Complete 10 tasks in one week.", "• Level 23 must."],
//     TaskStatus: "6/10",
//   },
//   {
//     id: 4,
//     IMG: images.Rewards5,
//     title: "Ut Hic",
//     detail: "rem et totam modi velit",
//     Status: "Incomplete",
//     points: "1x Golden Shield",
//     requriment: ["• Complete 10 tasks in one week.", "• Level 23 must."],
//     TaskStatus: "6/10",
//   },
//   {
//     id: 5,
//     IMG: images.Rewards3,
//     title: "At Et",
//     detail: "blanditiis accusamus facilis asperiores",
//     Status: "Incomplete",
//     Progress: "168/200",
//     points: "1x Shield",
//     requriment: ["• Complete 10 tasks in one week.", "• Level 23 must."],
//     TaskStatus: "6/10",
//   },
//   {
//     id: 6,
//     IMG: images.Rewards1,
//     title: "Quia Ad",
//     detail: "odio occaecati sit ut suscipit",
//     Status: "Incomplete",
//     Progress: "47/200",
//     points: "1x Golden Shield",
//     requriment: ["• Complete 10 tasks in one week.", "• Level 23 must."],
//     TaskStatus: "6/10",
//   },
//   {
//     id: 7,
//     IMG: images.Rewards2,
//     title: "Eligendi Est",
//     detail: "iure similique non aut cumque",
//     Status: "Incomplete",
//     Progress: "89/200",
//     points: "1x Cronw Shield",
//     requriment: ["• Complete 10 tasks in one week.", "• Level 23 must."],
//     TaskStatus: "6/10",
//   },
//   {
//     id: 8,
//     IMG: images.Rewards4,
//     title: "Ipsa Omnis",
//     detail: "debitis laudantium maiores qui animi",
//     Status: "Incomplete",
//     Progress: "63/200",
//     points: "500 Gold Bricks",
//     requriment: ["• Complete 10 tasks in one week.", "• Level 23 must."],
//     TaskStatus: "6/10",
//   },
//   {
//     id: 9,
//     IMG: images.Rewards5,
//     title: "Ut Hic",
//     detail: "rem et totam modi velit",
//     Status: "Incomplete",
//     points: "1x Golden Shield",
//     requriment: ["• Complete 10 tasks in one week.", "• Level 23 must."],
//     TaskStatus: "6/10",
//   },
//   {
//     id: 10,
//     IMG: images.Rewards3,
//     title: "At Et",
//     detail: "blanditiis accusamus facilis asperiores",
//     Status: "Incomplete",
//     Progress: "168/200",
//     points: "1x Shield",
//     requriment: ["• Complete 10 tasks in one week.", "• Level 23 must."],
//     TaskStatus: "6/10",
//   },
// ];
// export const Achievements = [
//   {
//     id: 1,
//     IMG: images.Rewards3,
//     title: "At Et",
//   },
//   {
//     id: 2,
//     IMG: images.Rewards1,
//     title: "Quia Ad",
//   },
//   {
//     id: 3,
//     IMG: images.Rewards2,
//     title: "Eligendi Est",
//   },

//   {
//     id: 4,
//     IMG: images.Rewards4,
//     title: "Ipsa Omnis",
//   },
//   {
//     id: 5,
//     IMG: images.Rewards5,
//     title: "Ut Hic",
//   },
// ];

// export const QuestLists = [
//   {
//     id: 1,
//     Title: "Dolor Qui Omnia",
//     description: "Renum corporis dolore. Ad provident magnam",
//     Time: "2:53 Pm",
//     date: "Wednesday, 13 April, 2021 09:00PM",
//     detail:
//       "Voluptate non error tempora sunt optio dolores labore dolorem. Dignissimos iste quam illo dignissimos rerum quia. Molestiae autem ut voluptas esse repellendus illum beatae. Vel nostrum nemo vero id veritatis tenetur saepe. Dignissimos iste quam illo dignissimos rerum quia. Dignissimos iste quam illo dignissimos rerum quia.",
//     status: "In-Progress",
//     Repeat: "Daily",
//     BlockApps: "Facebook,Whatspp,Instagram",
//   },
//   {
//     id: 2,
//     Title: "Unde Delectus Officia",
//     description: "Renum corporis dolore. Ad provident magnam",
//     Time: "2:53 Pm",
//     date: "Wednesday, 13 April, 2021 09:00PM",
//     detail:
//       "Voluptate non error tempora sunt optio dolores labore dolorem. Dignissimos iste quam illo dignissimos rerum quia. Molestiae autem ut voluptas esse repellendus illum beatae. Vel nostrum nemo vero id veritatis tenetur saepe. Dignissimos iste quam illo dignissimos rerum quia. Dignissimos iste quam illo dignissimos rerum quia.",
//     status: "In-Progress",
//     Repeat: "Daily",
//     BlockApps: "Facebook,Instagram",
//   },
//   {
//     id: 3,
//     Title: "Voluptatem Voluptas",
//     description: "Renum corporis dolore. Ad provident magnam",
//     Time: "2:53 Pm",
//     date: "Wednesday, 13 April, 2021 09:00PM",
//     detail:
//       "Voluptate non error tempora sunt optio dolores labore dolorem. Dignissimos iste quam illo dignissimos rerum quia. Molestiae autem ut voluptas esse repellendus illum beatae. Vel nostrum nemo vero id veritatis tenetur saepe. Dignissimos iste quam illo dignissimos rerum quia. Dignissimos iste quam illo dignissimos rerum quia.",
//     status: "In-Progress",
//     Repeat: "Daily",
//     BlockApps: "Whatspp,Instagram",
//   },
//   {
//     id: 4,
//     Title: "Nemo Deleniti Sit",
//     description: "Renum corporis dolore. Ad provident magnam",
//     Time: "2:53 Pm",
//     date: "Wednesday, 13 April, 2021 09:00PM",
//     detail:
//       "Voluptate non error tempora sunt optio dolores labore dolorem. Dignissimos iste quam illo dignissimos rerum quia. Molestiae autem ut voluptas esse repellendus illum beatae. Vel nostrum nemo vero id veritatis tenetur saepe. Dignissimos iste quam illo dignissimos rerum quia. Dignissimos iste quam illo dignissimos rerum quia.",
//     status: "In-Progress",
//     Repeat: "Daily",
//     BlockApps: "Whatspp,Instagram",
//   },
//   {
//     id: 5,
//     Title: "Dolor Qui Omnia",
//     description: "Renum corporis dolore. Ad provident magnam",
//     Time: "2:53 Pm",
//     date: "Wednesday, 13 April, 2021 09:00PM",
//     detail:
//       "Voluptate non error tempora sunt optio dolores labore dolorem. Dignissimos iste quam illo dignissimos rerum quia. Molestiae autem ut voluptas esse repellendus illum beatae. Vel nostrum nemo vero id veritatis tenetur saepe. Dignissimos iste quam illo dignissimos rerum quia. Dignissimos iste quam illo dignissimos rerum quia.",
//     status: "In-Progress",
//     Repeat: "Daily",
//     BlockApps: "Facebook,Whatspp,Instagram",
//   },
//   {
//     id: 6,
//     Title: "Unde Delectus Officia",
//     description: "Renum corporis dolore. Ad provident magnam",
//     Time: "2:53 Pm",
//     date: "Wednesday, 13 April, 2021 09:00PM",
//     detail:
//       "Voluptate non error tempora sunt optio dolores labore dolorem. Dignissimos iste quam illo dignissimos rerum quia. Molestiae autem ut voluptas esse repellendus illum beatae. Vel nostrum nemo vero id veritatis tenetur saepe. Dignissimos iste quam illo dignissimos rerum quia. Dignissimos iste quam illo dignissimos rerum quia.",
//     status: "In-Progress",
//     Repeat: "Daily",
//     BlockApps: "Facebook,Instagram",
//   },
//   {
//     id: 7,
//     Title: "Voluptatem Voluptas",
//     description: "Renum corporis dolore. Ad provident magnam",
//     Time: "2:53 Pm",
//     date: "Wednesday, 13 April, 2021 09:00PM",
//     detail:
//       "Voluptate non error tempora sunt optio dolores labore dolorem. Dignissimos iste quam illo dignissimos rerum quia. Molestiae autem ut voluptas esse repellendus illum beatae. Vel nostrum nemo vero id veritatis tenetur saepe. Dignissimos iste quam illo dignissimos rerum quia. Dignissimos iste quam illo dignissimos rerum quia.",
//     status: "In-Progress",
//     Repeat: "Daily",
//     BlockApps: "Whatspp,Instagram",
//   },
//   {
//     id: 8,
//     Title: "Nemo Deleniti Sit",
//     description: "Renum corporis dolore. Ad provident magnam",
//     Time: "2:53 Pm",
//     date: "Wednesday, 13 April, 2021 09:00PM",
//     detail:
//       "Voluptate non error tempora sunt optio dolores labore dolorem. Dignissimos iste quam illo dignissimos rerum quia. Molestiae autem ut voluptas esse repellendus illum beatae. Vel nostrum nemo vero id veritatis tenetur saepe. Dignissimos iste quam illo dignissimos rerum quia. Dignissimos iste quam illo dignissimos rerum quia.",
//     status: "In-Progress",
//     Repeat: "Daily",
//     BlockApps: "Whatspp,Instagram",
//   },
//   {
//     id: 9,
//     Title: "Dolor Qui Omnia",
//     description: "Renum corporis dolore. Ad provident magnam",
//     Time: "2:53 Pm",
//     date: "Wednesday, 13 April, 2021 09:00PM",
//     detail:
//       "Voluptate non error tempora sunt optio dolores labore dolorem. Dignissimos iste quam illo dignissimos rerum quia. Molestiae autem ut voluptas esse repellendus illum beatae. Vel nostrum nemo vero id veritatis tenetur saepe. Dignissimos iste quam illo dignissimos rerum quia. Dignissimos iste quam illo dignissimos rerum quia.",
//     status: "In-Progress",
//     Repeat: "Daily",
//     BlockApps: "Facebook,Whatspp,Instagram",
//   },
//   {
//     id: 10,
//     Title: "Unde Delectus Officia",
//     description: "Renum corporis dolore. Ad provident magnam",
//     Time: "2:53 Pm",
//     date: "Wednesday, 13 April, 2021 09:00PM",
//     detail:
//       "Voluptate non error tempora sunt optio dolores labore dolorem. Dignissimos iste quam illo dignissimos rerum quia. Molestiae autem ut voluptas esse repellendus illum beatae. Vel nostrum nemo vero id veritatis tenetur saepe. Dignissimos iste quam illo dignissimos rerum quia. Dignissimos iste quam illo dignissimos rerum quia.",
//     status: "In-Progress",
//     Repeat: "Daily",
//     BlockApps: "Facebook,Instagram",
//   },
//   {
//     id: 7,
//     Title: "Voluptatem Voluptas",
//     description: "Renum corporis dolore. Ad provident magnam",
//     Time: "2:53 Pm",
//     date: "Wednesday, 13 April, 2021 09:00PM",
//     detail:
//       "Voluptate non error tempora sunt optio dolores labore dolorem. Dignissimos iste quam illo dignissimos rerum quia. Molestiae autem ut voluptas esse repellendus illum beatae. Vel nostrum nemo vero id veritatis tenetur saepe. Dignissimos iste quam illo dignissimos rerum quia. Dignissimos iste quam illo dignissimos rerum quia.",
//     status: "In-Progress",
//     Repeat: "Daily",
//     BlockApps: "Whatspp,Instagram",
//   },
//   {
//     id: 8,
//     Title: "Nemo Deleniti Sit",
//     description: "Renum corporis dolore. Ad provident magnam",
//     Time: "2:53 Pm",
//     date: "Wednesday, 13 April, 2021 09:00PM",
//     detail:
//       "Voluptate non error tempora sunt optio dolores labore dolorem. Dignissimos iste quam illo dignissimos rerum quia. Molestiae autem ut voluptas esse repellendus illum beatae. Vel nostrum nemo vero id veritatis tenetur saepe. Dignissimos iste quam illo dignissimos rerum quia. Dignissimos iste quam illo dignissimos rerum quia.",
//     status: "In-Progress",
//     Repeat: "Daily",
//     BlockApps: "Whatspp,Instagram",
//   },
// ];

// export const userStregnth = [
//   {
//     id: 1,
//     title: "Strength",
//     power: "86",
//   },
//   {
//     id: 2,
//     title: "Agility",
//     power: "58",
//   },
//   {
//     id: 3,
//     title: "Stamina",
//     power: "76",
//   },
//   {
//     id: 4,
//     title: "Vitality",
//     power: "25",
//   },
//   {
//     id: 5,
//     title: "Intelligence",
//     power: "96",
//   },
//   {
//     id: 6,
//     title: "Wisdom",
//     power: "43",
//   },
//   {
//     id: 7,
//     title: "Faith",
//     power: "30",
//   },
//   {
//     id: 8,
//     title: "Discipline",
//     power: "20",
//   },
// ];
// export const Inventory = [
//   {
//     id: 1,
//     title: "Armour",
//     IMG: images.Armour,
//   },
//   {
//     id: 3,
//     title: "Weapon",
//     IMG: images.Sword,
//   },
//   {
//     id: 3,
//     title: "Helmet",
//     IMG: images.helmet,
//   },
//   {
//     id: 4,
//     title: "Shield",
//     IMG: images.Sheild,
//   },
//   {
//     id: 5,
//     title: "Cape",
//     IMG: images.Cape,
//   },
//   {
//     id: 6,
//     title: "Hat",
//     IMG: images.hat,
//   },
//   {
//     id: 7,
//     title: "Mask",
//     IMG: images.Mask,
//   },
//   {
//     id: 8,
//     title: "Glasses",
//     IMG: images.Glasses,
//   },
// ];
// export const SWORDS = [
//   {
//     id: 1,
//     IMG: require("../assets/Weapons/Axe/DreadCleaver.png"),
//     Title: "Dread Cleaver",
//     Price: "10K",
//     Strenght: "28",
//     health: "39",
//     isSelect: true,
//   },
//   {
//     id: 2,
//     IMG: require("../assets/Weapons/Axe/RunicAxe.png"),
//     Title: "Runic Axe",
//     Price: "1K",
//     Strenght: "18",
//     health: "40",
//     isSelect: false,
//   },
//   {
//     id: 3,
//     IMG: require("../assets/Weapons/Axe/SmallAxe.png"),
//     Title: "Small Axe",
//     Price: "3K",
//     Strenght: "20",
//     health: "48",
//     isSelect: false,
//   },
//   {
//     id: 4,
//     IMG: require("../assets/Weapons/Axe/StoneAxe.png"),
//     Title: "Stone Axe",
//     Price: "5K",
//     Strenght: "28",
//     health: "41",
//     isSelect: false,
//   },
//   {
//     id: 5,
//     IMG: require("../assets/Weapons/Axe/WoodcutterAxe.png"),
//     Title: "Woodcutter Axe",
//     Price: "7K",
//     Strenght: "25",
//     health: "40",
//     isSelect: false,
//   },
//   {
//     id: 6,
//     IMG: require("../assets/Weapons/Basic/Hammer/BlackHammer.png"),
//     Title: "BlackHammer",
//     Price: "8K",
//     Strenght: "23",
//     health: "43",
//     isSelect: false,
//   },
//   {
//     id: 7,
//     IMG: require("../assets/Weapons/Hammer/WarHammer.png"),
//     Title: "WarHammer",
//     Price: "8K",
//     Strenght: "23",
//     health: "43",
//     isSelect: false,
//   },
//   {
//     id: 8,
//     IMG: require("../assets/Weapons/Hammer/WoodenClub.png"),
//     Title: "WoodenClub",
//     Price: "8K",
//     Strenght: "23",
//     health: "43",
//     isSelect: false,
//   },
//   {
//     id: 9,
//     IMG: require("../assets/Weapons/Shield/Knights/BlueKnightShield.png"),
//     Title: "BlueKnight Shield",
//     Price: "8K",
//     Strenght: "23",
//     health: "43",
//     isSelect: false,
//   },
//   {
//     id: 10,
//     IMG: require("../assets/Weapons/Shield/Knights/CrusaderShield.png"),
//     Title: "Crusader Shield",
//     Price: "8K",
//     Strenght: "23",
//     health: "43",
//     isSelect: false,
//   },
//   {
//     id: 11,
//     IMG: require("../assets/Weapons/Shield/Knights/SteelShield.png"),
//     Title: "Steel Shield",
//     Price: "8K",
//     Strenght: "23",
//     health: "43",
//     isSelect: false,
//   },
// ];
// export const BodyAppear = [
//   {
//     id: 1,
//     title: "Body",
//     IMG: require("../assets/BodyCategory/Body.png"),
//   },
//   {
//     id: 2,
//     title: "Mouth",
//     IMG: require("../assets/BodyCategory/Mouth.png"),
//   },
//   {
//     id: 3,
//     title: "Hair",
//     IMG: require("../assets/BodyCategory/manhair.png"),
//   },
//   {
//     id: 4,
//     title: "Beard",
//     IMG: require("../assets/BodyCategory/beard.png"),
//   },
//   {
//     id: 5,
//     title: "Eyes",
//     IMG: require("../assets/BodyCategory/eye-open.png"),
//   },
//   {
//     id: 6,
//     title: "Eyebrows",
//     IMG: require("../assets/BodyCategory/eye-closed.png"),
//   },
//   {
//     id: 7,
//     title: "Ears",
//     IMG: require("../assets/BodyCategory/ear.png"),
//   },
//   {
//     id: 8,
//     title: "Head",
//     IMG: require("../assets/BodyCategory/headView.png"),
//   },
// ];
// export const BodyData = [
//   {
//     id: 17,
//     IMG: require("../assets/Appear/Body/angelwings_c.png"),
//     Title: "Fire Wings",
//     Price: "2K",
//     Strenght: "28",
//     health: "39",
//     isSelect: true,
//     isPrice: false,
//     type: "Body",
//   },
//   {
//     id: 18,
//     IMG: require("../assets/Appear/Body/angelwings_b.png"),
//     Title: "Angel Wings",
//     Price: "2K",
//     Strenght: "28",
//     health: "39",
//     isPrice: false,
//     isSelect: true,
//     type: "Body",
//   },
//   {
//     id: 1,
//     IMG: require("../assets/Appear/Mouth/1.png"),
//     Title: "Smile",
//     Price: "10K",
//     Strenght: "28",
//     health: "39",
//     isSelect: true,
//     type: "Mouth",
//     isPrice: false,
//   },
//   {
//     id: 2,
//     IMG: require("../assets/Appear/Hair/1.png"),
//     Title: "Buzz Out",
//     Price: "1K",
//     Strenght: "18",
//     health: "40",
//     isSelect: false,
//     type: "Hair",
//     isPrice: true,
//   },
//   {
//     id: 3,
//     IMG: require("../assets/Appear/Hair/2.png"),
//     Title: "Leaky",
//     Price: "3K",
//     Strenght: "20",
//     health: "48",
//     isSelect: false,
//     type: "Hair",
//     isPrice: false,
//   },
//   {
//     id: 4,
//     IMG: require("../assets/Appear/Hair/3.png"),
//     Title: "Mohwak",
//     Price: "3K",
//     Strenght: "28",
//     health: "41",
//     isSelect: false,
//     type: "Hair",
//     isPrice: true,
//   },

//   {
//     id: 5,
//     IMG: require("../assets/Appear/Hair/4.png"),
//     Title: "Fame",
//     Price: "5K",
//     Strenght: "25",
//     health: "40",
//     isSelect: false,
//     type: "Hair",
//     isPrice: false,
//   },
//   {
//     id: 6,
//     IMG: require("../assets/Appear/Hair/5.png"),
//     Title: "Silver Cut",
//     Price: "7K",
//     Strenght: "23",
//     health: "43",
//     isSelect: false,
//     type: "Hair",
//     isPrice: false,
//   },
//   {
//     id: 7,
//     IMG: require("../assets/Appear/Mouth/2.png"),
//     Title: "Sharp",
//     Price: "1K",
//     Strenght: "28",
//     health: "39",
//     isSelect: true,
//     type: "Mouth",
//     isPrice: false,
//   },
//   {
//     id: 8,
//     IMG: require("../assets/Appear/Mouth/3.png"),
//     Title: "Sad",
//     Price: "1K",
//     Strenght: "28",
//     health: "39",
//     isSelect: true,
//     type: "Mouth",
//     isPrice: false,
//   },
//   {
//     id: 9,
//     IMG: require("../assets/Appear/Mouth/4.png"),
//     Title: "Smile",
//     Price: "4K",
//     Strenght: "28",
//     health: "39",
//     isSelect: true,
//     type: "Mouth",
//     isPrice: false,
//   },
//   {
//     id: 10,
//     IMG: require("../assets/Appear/Mouth/5.png"),
//     Title: "Smile",
//     Price: "8K",
//     Strenght: "28",
//     health: "39",
//     isSelect: true,
//     type: "Mouth",
//     isPrice: false,
//   },
//   {
//     id: 61,
//     IMG: require("../assets/Appear/Ears/ear1.png"),
//     Title: "Ears",
//     Price: "4K",
//     Strenght: "28",
//     health: "39",
//     isSelect: true,
//     type: "Ears",
//     isPrice: false,
//   },
//   {
//     id: 11,
//     IMG: require("../assets/Appear/Ears/ear2.png"),
//     Title: "Ears",
//     Price: "1K",
//     Strenght: "28",
//     health: "39",
//     isSelect: true,
//     type: "Ears",
//     isPrice: false,
//   },
//   {
//     id: 12,
//     IMG: require("../assets/Appear/Eye/eyes1.png"),
//     Title: "Shock",
//     Price: "2K",
//     Strenght: "28",
//     health: "39",
//     isSelect: true,
//     isPrice: false,
//     type: "Eyes",
//   },
//   {
//     id: 13,
//     IMG: require("../assets/Appear/Eye/eyes2.png"),
//     Title: "Eyes",
//     Price: "2K",
//     Strenght: "28",
//     health: "39",
//     isSelect: true,
//     isPrice: false,

//     type: "Eyes",
//   },
//   {
//     id: 14,
//     IMG: require("../assets/Appear/Eye/eyes3.png"),
//     Title: "Heart Eyes",
//     Price: "6K",
//     Strenght: "28",
//     health: "39",
//     isSelect: true,
//     isPrice: false,

//     type: "Eyes",
//   },
//   {
//     id: 15,
//     IMG: require("../assets/Appear/Eye/eyes4.png"),
//     Title: "Eyes",
//     Price: "10K",
//     Strenght: "28",
//     health: "39",
//     isSelect: true,
//     isPrice: false,

//     type: "Eyes",
//   },
//   {
//     id: 16,
//     IMG: require("../assets/Appear/Facehead/Face1.png"),
//     Title: "Head",
//     Price: "1K",
//     Strenght: "28",
//     health: "39",
//     isPrice: false,
//     isSelect: true,
//     type: "Head",
//   },

//   {
//     id: 19,
//     IMG: require("../assets/Appear/Hair/6.png"),
//     Title: "Mohwak 2",
//     Price: "5K",
//     Strenght: "28",
//     health: "41",
//     isSelect: false,
//     type: "Hair",
//     isPrice: false,
//   },
//   {
//     id: 20,
//     IMG: require("../assets/Appear/Hair/7.png"),
//     Title: "Mohwak",
//     Price: "2K",
//     Strenght: "28",
//     health: "41",
//     isSelect: false,
//     type: "Hair",
//     isPrice: false,
//   },
//   {
//     id: 21,
//     IMG: require("../assets/Appear/Hair/8.png"),
//     Title: "Side cut",
//     Price: "5K",
//     Strenght: "28",
//     health: "41",
//     isSelect: false,
//     type: "Hair",
//     isPrice: true,
//   },
//   {
//     id: 22,
//     IMG: require("../assets/Appear/Eye/eyes3.png"),
//     Title: "Soul Eyes",
//     Price: "10K",
//     Strenght: "28",
//     health: "39",
//     isSelect: true,
//     isPrice: true,
//     type: "Eyes",
//   },
//   {
//     id: 23,
//     IMG: require("../assets/Appear/Eye/eyes6.png"),
//     Title: "Sad Eyes",
//     Price: "1K",
//     Strenght: "28",
//     health: "39",
//     isSelect: true,
//     isPrice: true,
//     type: "Eyes",
//   },
//   {
//     id: 24,
//     IMG: require("../assets/Appear/Ears/1.png"),
//     Title: "Ears",
//     Price: "1K",
//     Strenght: "28",
//     health: "39",
//     isSelect: true,
//     type: "Ears",
//     isPrice: true,
//   },
//   {
//     id: 24,
//     IMG: require("../assets/Appear/Ears/2.png"),
//     Title: "Ears",
//     Price: "4K",
//     Strenght: "28",
//     health: "39",
//     isSelect: true,
//     type: "Ears",
//     isPrice: true,
//   },
//   {
//     id: 25,
//     IMG: require("../assets/Appear/Facehead/Face1.png"),
//     Title: "Oval Head",
//     Price: "3K",
//     Strenght: "28",
//     health: "39",
//     isPrice: true,
//     isSelect: true,
//     type: "Head",
//   },
//   {
//     id: 26,
//     IMG: require("../assets/Appear/Mouth/6.png"),
//     Title: "Smiling",
//     Price: "1K",
//     Strenght: "28",
//     health: "39",
//     isSelect: true,
//     type: "Mouth",
//     isPrice: true,
//   },
//   {
//     id: 27,
//     IMG: require("../assets/Appear/Mouth/7.png"),
//     Title: "Pink",
//     Price: "5K",
//     Strenght: "28",
//     health: "39",
//     isSelect: true,
//     type: "Mouth",
//     isPrice: true,
//   },
//   {
//     id: 28,
//     IMG: require("../assets/Appear/Mouth/8.png"),
//     Title: "Wink",
//     Price: "1K",
//     Strenght: "28",
//     health: "39",
//     isSelect: true,
//     type: "Mouth",
//     isPrice: true,
//   },
//   {
//     id: 29,
//     IMG: require("../assets/Appear/Hair/9.png"),
//     Title: "Buzz Out",
//     Price: "1K",
//     Strenght: "18",
//     health: "40",
//     isSelect: false,
//     type: "Hair",
//     isPrice: true,
//   },
//   {
//     id: 30,
//     IMG: require("../assets/Appear/Hair/10.png"),
//     Title: "Buzz Out",
//     Price: "1K",
//     Strenght: "18",
//     health: "40",
//     isSelect: false,
//     type: "Hair",
//     isPrice: true,
//   },
//   {
//     id: 31,
//     IMG: require("../assets/Appear/Hair/11.png"),
//     Title: "Baby Cut",
//     Price: "1K",
//     Strenght: "18",
//     health: "40",
//     isSelect: false,
//     type: "Hair",
//     isPrice: false,
//   },
//   {
//     id: 32,
//     IMG: require("../assets/Appear/Hair/12.png"),
//     Title: "Bob Cut",
//     Price: "1K",
//     Strenght: "18",
//     health: "40",
//     isSelect: false,
//     type: "Hair",
//     isPrice: true,
//   },
//   {
//     id: 33,
//     IMG: require("../assets/Appear/Hair/13.png"),
//     Title: "Buzz Out",
//     Price: "1K",
//     Strenght: "18",
//     health: "40",
//     isSelect: false,
//     type: "Hair",
//     isPrice: false,
//   },
//   {
//     id: 34,
//     IMG: require("../assets/Appear/Hair/14.png"),
//     Title: "Bob Cut",
//     Price: "1K",
//     Strenght: "18",
//     health: "40",
//     isSelect: false,
//     type: "Hair",
//     isPrice: true,
//   },
//   {
//     id: 35,
//     IMG: require("../assets/Appear/Hair/15.png"),
//     Title: "Pixie Cut",
//     Price: "1K",
//     Strenght: "18",
//     health: "40",
//     isSelect: false,
//     type: "Hair",
//     isPrice: false,
//   },
//   {
//     id: 36,
//     IMG: require("../assets/Appear/Hair/16.png"),
//     Title: "Wispy Out",
//     Price: "1K",
//     Strenght: "18",
//     health: "40",
//     isSelect: false,
//     type: "Hair",
//     isPrice: true,
//   },
//   {
//     id: 37,
//     IMG: require("../assets/Appear/Hair/17.png"),
//     Title: "V Cut",
//     Price: "1K",
//     Strenght: "18",
//     health: "40",
//     isSelect: false,
//     type: "Hair",
//     isPrice: true,
//   },
//   {
//     id: 38,
//     IMG: require("../assets/Appear/Hair/18.png"),
//     Title: "Straight Cut",
//     Price: "3K",
//     Strenght: "18",
//     health: "40",
//     isSelect: false,
//     type: "Hair",
//     isPrice: true,
//   },
//   {
//     id: 39,
//     IMG: require("../assets/Appear/Hair/19.png"),
//     Title: "Step Cut",
//     Price: "1K",
//     Strenght: "18",
//     health: "40",
//     isSelect: false,
//     type: "Hair",
//     isPrice: false,
//   },
//   {
//     id: 40,
//     IMG: require("../assets/Appear/Hair/20.png"),
//     Title: "Buzz Out",
//     Price: "1K",
//     Strenght: "18",
//     health: "40",
//     isSelect: false,
//     type: "Hair",
//     isPrice: true,
//   },
//   {
//     id: 41,
//     IMG: require("../assets/Appear/Hair/hair1.png"),
//     Title: "Hair",
//     Price: "1K",
//     Strenght: "18",
//     health: "40",
//     isSelect: false,
//     type: "Hair",
//     isPrice: false,
//   },
//   {
//     id: 42,
//     IMG: require("../assets/Appear/Hair/hair2.png"),
//     Title: "Play",
//     Price: "1K",
//     Strenght: "18",
//     health: "40",
//     isSelect: false,
//     type: "Hair",
//     isPrice: false,
//   },
//   {
//     id: 43,
//     IMG: require("../assets/Appear/Hair/hair3.png"),
//     Title: "Buzz Out",
//     Price: "1K",
//     Strenght: "18",
//     health: "40",
//     isSelect: false,
//     type: "Hair",
//     isPrice: false,
//   },
//   {
//     id: 44,
//     IMG: require("../assets/Appear/Hair/hair4.png"),
//     Title: "Curly",
//     Price: "1K",
//     Strenght: "18",
//     health: "40",
//     isSelect: false,
//     type: "Hair",
//     isPrice: true,
//   },
//   {
//     id: 45,
//     IMG: require("../assets/Appear/Hair/hair5.png"),
//     Title: "wavy",
//     Price: "1K",
//     Strenght: "18",
//     health: "40",
//     isSelect: false,
//     type: "Hair",
//     isPrice: false,
//   },
//   {
//     id: 46,
//     IMG: require("../assets/Appear/Hair/hair6.png"),
//     Title: "Baby Cut",
//     Price: "2K",
//     Strenght: "18",
//     health: "40",
//     isSelect: false,
//     type: "Hair",
//     isPrice: true,
//   },
//   {
//     id: 47,
//     IMG: require("../assets/Appear/Hair/hair7.png"),
//     Title: "Koeron Cut",
//     Price: "1K",
//     Strenght: "18",
//     health: "40",
//     isSelect: false,
//     type: "Hair",
//     isPrice: true,
//   },
//   {
//     id: 48,
//     IMG: require("../assets/Appear/Hair/hair8.png"),
//     Title: "Under Out",
//     Price: "1K",
//     Strenght: "18",
//     health: "40",
//     isSelect: false,
//     type: "Hair",
//     isPrice: false,
//   },
//   {
//     id: 49,
//     IMG: require("../assets/Appear/Facehead/2.png"),
//     Title: "Injured Head",
//     Price: "1K",
//     Strenght: "28",
//     health: "39",
//     isPrice: false,
//     isSelect: true,
//     type: "Head",
//   },
//   {
//     id: 50,
//     IMG: require("../assets/Appear/Facehead/3.png"),
//     Title: "Head",
//     Price: "1K",
//     Strenght: "28",
//     health: "39",
//     isPrice: true,
//     isSelect: true,
//     type: "Head",
//   },
//   {
//     id: 51,
//     IMG: require("../assets/Appear/Facehead/4.png"),
//     Title: "Danger",
//     Price: "1K",
//     Strenght: "28",
//     health: "39",
//     isPrice: false,
//     isSelect: true,
//     type: "Head",
//   },
//   {
//     id: 52,
//     IMG: require("../assets/Appear/Facehead/1-colored.png"),
//     Title: "Yellow Head",
//     Price: "1K",
//     Strenght: "28",
//     health: "39",
//     isPrice: true,
//     isSelect: true,
//     type: "Head",
//   },
//   {
//     id: 53,
//     IMG: require("../assets/Appear/Eye/1-2.png"),
//     Title: "Angry",
//     Price: "1K",
//     Strenght: "28",
//     health: "39",
//     isSelect: true,
//     isPrice: true,
//     type: "Eyes",
//   },
//   {
//     id: 54,
//     IMG: require("../assets/Appear/Eye/2.png"),
//     Title: "Eyes",
//     Price: "1K",
//     Strenght: "28",
//     health: "39",
//     isSelect: true,
//     isPrice: false,
//     type: "Eyes",
//   },
//   {
//     id: 55,
//     IMG: require("../assets/Appear/Eye/3.png"),
//     Title: "Style",
//     Price: "1K",
//     Strenght: "28",
//     health: "39",
//     isSelect: true,
//     isPrice: true,
//     type: "Eyes",
//   },
//   {
//     id: 56,
//     IMG: require("../assets/Appear/Eye/4.png"),
//     Title: "Sad Eyes",
//     Price: "1K",
//     Strenght: "28",
//     health: "39",
//     isSelect: true,
//     isPrice: true,
//     type: "Eyes",
//   },
//   {
//     id: 57,
//     IMG: require("../assets/Appear/Eye/5.png"),
//     Title: "Crazy",
//     Price: "1K",
//     Strenght: "28",
//     health: "39",
//     isSelect: true,
//     isPrice: true,
//     type: "Eyes",
//   },
//   {
//     id: 58,
//     IMG: require("../assets/Appear/Eye/6.png"),
//     Title: "Sad",
//     Price: "1K",
//     Strenght: "28",
//     health: "39",
//     isSelect: true,
//     isPrice: true,
//     type: "Eyes",
//   },
//   {
//     id: 59,
//     IMG: require("../assets/Appear/Eye/7.png"),
//     Title: "Sleep",
//     Price: "1K",
//     Strenght: "28",
//     health: "39",
//     isSelect: true,
//     isPrice: true,
//     type: "Eyes",
//   },
//   {
//     id: 60,
//     IMG: require("../assets/Appear/Eye/8.png"),
//     Title: "No hope",
//     Price: "1K",
//     Strenght: "28",
//     health: "39",
//     isSelect: true,
//     isPrice: false,
//     type: "Eyes",
//   },
//   {
//     id: 62,
//     IMG: require("../assets/Appear/Eye/9.png"),
//     Title: "Sleepy Eyes",
//     Price: "1K",
//     Strenght: "28",
//     health: "39",
//     isSelect: true,
//     isPrice: false,
//     type: "Eyes",
//   },
//   {
//     id: 64,
//     IMG: require("../assets/Appear/Ears/3.png"),
//     Title: "Ears",
//     Price: "4K",
//     Strenght: "28",
//     health: "39",
//     isSelect: true,
//     type: "Ears",
//     isPrice: true,
//   },
//   {
//     id: 65,
//     IMG: require("../assets/Appear/Ears/4.png"),
//     Title: "Ears",
//     Price: "4K",
//     Strenght: "28",
//     health: "39",
//     isSelect: true,
//     type: "Ears",
//     isPrice: true,
//   },
//   {
//     id: 64,
//     IMG: require("../assets/Appear/Ears/5.png"),
//     Title: "Ears",
//     Price: "4K",
//     Strenght: "28",
//     health: "39",
//     isSelect: true,
//     type: "Ears",
//     isPrice: false,
//   },
//   {
//     id: 64,
//     IMG: require("../assets/Appear/Ears/6.png"),
//     Title: "Ears",
//     Price: "4K",
//     Strenght: "28",
//     health: "39",
//     isSelect: true,
//     type: "Ears",
//     isPrice: false,
//   },
//   {
//     id: 65,
//     IMG: require("../assets/Appear/Mouth/9.png"),
//     Title: "Tease",
//     Price: "1K",
//     Strenght: "28",
//     health: "39",
//     isSelect: true,
//     type: "Mouth",
//     isPrice: true,
//   },
//   {
//     id: 66,
//     IMG: require("../assets/Appear/Mouth/Mouth1.png"),
//     Title: "Open Mouth",
//     Price: "1K",
//     Strenght: "28",
//     health: "39",
//     isSelect: true,
//     type: "Mouth",
//     isPrice: true,
//   },
//   {
//     id: 67,
//     IMG: require("../assets/Appear/Mouth/Mouth2.png"),
//     Title: "Tease",
//     Price: "1K",
//     Strenght: "28",
//     health: "39",
//     isSelect: true,
//     type: "Mouth",
//     isPrice: true,
//   },
//   {
//     id: 68,
//     IMG: require("../assets/Appear/Mouth/Mouth3.png"),
//     Title: "Happy",
//     Price: "1K",
//     Strenght: "28",
//     health: "39",
//     isSelect: true,
//     type: "Mouth",
//     isPrice: false,
//   },
//   {
//     id: 69,
//     IMG: require("../assets/Appear/Mouth/Mouth4.png"),
//     Title: "Surprise",
//     Price: "1K",
//     Strenght: "28",
//     health: "39",
//     isSelect: true,
//     type: "Mouth",
//     isPrice: true,
//   },
//   {
//     id: 70,
//     IMG: require("../assets/Appear/Mouth/Mouth5.png"),
//     Title: "tongue",
//     Price: "1K",
//     Strenght: "28",
//     health: "39",
//     isSelect: true,
//     type: "Mouth",
//     isPrice: true,
//   },
//   {
//     id: 71,
//     IMG: require("../assets/Appear/Mouth/Mouth6.png"),
//     Title: "Anger",
//     Price: "1K",
//     Strenght: "28",
//     health: "39",
//     isSelect: true,
//     type: "Mouth",
//     isPrice: true,
//   },
//   {
//     id: 72,
//     IMG: require("../assets/Appear/Mouth/Mouth7.png"),
//     Title: "Bright smile",
//     Price: "1K",
//     Strenght: "28",
//     health: "39",
//     isSelect: true,
//     type: "Mouth",
//     isPrice: false,
//   },
//   {
//     id: 73,
//     IMG: require("../assets/Appear/Body/MountainHelmPaint.png"),
//     Title: "Mountain Helm Wings",
//     Price: "2K",
//     Strenght: "28",
//     health: "39",
//     isPrice: true,
//     isSelect: true,
//     type: "Body",
//   },
//   {
//     id: 74,
//     IMG: require("../assets/Appear/Body/DarkMountainPaint.png"),
//     Title: "Dark Mountain",
//     Price: "2K",
//     Strenght: "28",
//     health: "39",
//     isPrice: true,
//     isSelect: true,
//     type: "Body",
//   },
//   {
//     id: 73,
//     IMG: require("../assets/Appear/Body/VikingIronHelm1.png"),
//     Title: "Viking Iron Helm",
//     Price: "2K",
//     Strenght: "28",
//     health: "39",
//     isPrice: true,
//     isSelect: true,
//     type: "Body",
//   },
// ];
